version: '3.7'

services:
  db:
    image: postgres:11.7
    restart: always
    volumes:
      - ./tmp/postgres_data:/var/lib/postgresql/data
    ports:
      - '5431:5432'
    environment:
      LANG: 'en_US.UTF-8'
      LANGUAGE: 'en_US:en'
      LC_ALL: 'en_US.UTF-8'
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password

  api:
    image: api
    build:
      context: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    container_name: api
    hostname: api
    stdin_open: true
    tty: true
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
    env_file: .env
    environment:
      DATABASE_URL: postgres://postgres:password@db/query_helper_demo_development
      RACK_ENV: development
      RAILS_ENV: development
    logging:
      options:
        max-size: 10m
        max-file: "5"

volumes:
  db:
